name: Build and Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release (win-x64)
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Test
      run: dotnet test CapsLockLanguageChanger.slnx --no-restore

    - name: Publish
      run: >
        dotnet publish ./src/CapsLockLanguageChanger/CapsLockLanguageChanger.csproj
        -c Release
        -p:DebugType=None
        -p:DebugSymbols=false
        -o ./publish

    - name: Package
      run: |
        $exePath = "./publish/CapsLockLanguageChanger.exe"
        $targetName = "./publish/CapsLockLanguageChanger-win-x64.exe"
        $zipName = "./publish/CapsLockLanguageChanger-${{ github.ref_name }}-win-x64.zip"

        Move-Item -Path $exePath -Destination $targetName

        Compress-Archive -Path $targetName -DestinationPath $zipName

    - name: Upload to Release
      uses: softprops/action-gh-release@v3
      with:
        files: |
          ./publish/*.zip
          ./publish/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
